function f = observablesRoessler(in1)
%observablesRoessler
%    F = observablesRoessler(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Feb-2023 12:56:14

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = x1.^2;
t3 = x2.^2;
t4 = x3.^2;
f = [x1;x2;x3;0.0;1.0;x1;x2;x3;1.0;x1;x2;x3;1.0;x1;x2;x3;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;t4;x2.*x3;t4.*x2;t3;t3.*x3;t3.*t4;x1.*x3;t4.*x1;x1.*x2;x1.*x2.*x3;t4.*x1.*x2;t3.*x1;t3.*x1.*x3;t3.*t4.*x1;t2;t2.*x3;t2.*t4;t2.*x2;t2.*x2.*x3;t2.*t4.*x2;t2.*t3;t2.*t3.*x3];
